#!/bin/bash
set -o errexit -o nounset -o pipefail

# MotionPhoto Remover
# Note that this does not remove the metadata (EXIV/XMP) for motion photos

originalFilePath="$1"
#DELETE_BACKUP_IN_DAYS=${DELETE_BACKUP_IN_DAYS:-30}

if [[ -z "${originalFilePath}" ]]; then
    echo "No argument supplied."
    exit 1
fi

BASEDIR=$(dirname $0)
ABSOLUTE_BASEDIR="$(cd $BASEDIR && pwd)"
source "${ABSOLUTE_BASEDIR}/moPhoLib.sh"

if isMotionPhoto "${originalFilePath}"; then
  newFilePath="${originalFilePath//.MP/}"
  rsync -a "$originalFilePath" "${newFilePath}"

  ofs=$(findOffset "${newFilePath}")
  truncate -s $((ofs - 4)) "${newFilePath}"

  trashedPath=$(rmFile "${originalFilePath}")
  
  if command -v termux-media-scan >/dev/null; then
    termux-media-scan "${newFilePath}" "${trashedPath}" >/dev/null
  fi
  
  echo "Removed video from motion photo ${newFilePath}"
  echo "Moved original to ${trashedPath}, to be deleted in ${DELETE_BACKUP_IN_DAYS} days"
else
    echo "No video found in file $originalFilePath"
    exit 2
fi