#!/bin/bash

# MotionPhoto Remover

DELETE_BACKUP_IN_DAYS=30

originalFilePath="$1"

if [[ -z "${originalFilePath}" ]]; then
    echo "No argument supplied."
    exit 1
fi

ofs=$(grep --byte-offset --only-matching --text "ftypmp4\|ftypisom" "${originalFilePath}")
ofs=${ofs%:*}

if [[ -n "$ofs" ]]; then
  newFilePath="${originalFilePath//.MP/}"
  rsync -a "$originalFilePath" "${newFilePath}"

  ofs=$(grep --byte-offset --only-matching --text "ftypmp4\|ftypisom" "${newFilePath}")
  ofs=${ofs%:*}

  truncate -s $((ofs - 4)) "${newFilePath}"

  folder=$(dirname "${originalFilePath}")
  baseFileName=$(basename "${originalFilePath}")
  deletionDate="$(($(date +%s) + "$DELETE_BACKUP_IN_DAYS" * 86400))"
  trashedPath="${folder}/.trashed-${deletionDate}-${baseFileName}"
  mv "${originalFilePath}" "${trashedPath}"

  if command -v termux-media-scan >/dev/null; then
    termux-media-scan "${newFilePath}" "$trashedPath" >/dev/null
  fi
  
  echo "Removed video from motion photo  ${newFilePath}"
  echo
  echo "Moved original to $trashedPath, to be deleted in $DELETE_BACKUP_IN_DAYS days"
else
    echo "No video found in file $originalFilePath"
    exit 2
fi