#!/bin/bash
set -o errexit -o nounset -o pipefail
# MotionPhoto Extractor

originalFilePath="$1"

if [[ -z "${originalFilePath}" ]]; then
    echo "No argument supplied."
    exit 1
fi

BASEDIR=$(dirname $0)
ABSOLUTE_BASEDIR="$(cd $BASEDIR && pwd)"
source "${ABSOLUTE_BASEDIR}/moPhoLib.sh"

if isMotionPhoto "${originalFilePath}"; then
  newFilePath="${originalFilePath%.MP.jpg}.mp4"
  extractVideo "${originalFilePath}" "${newFilePath}"
  
  if command -v termux-media-scan >/dev/null; then
    termux-media-scan -r "${newFilePath}"
  fi
  
  echo "extracted video from motion photo to ${newFilePath}"
else
    echo "No video found in file $originalFilePath"
    exit 2
fi