#!/bin/bash
set -o errexit -o nounset -o pipefail

# MotionPhoto Extractor

originalFilePath="$1"

if [[ -z "${originalFilePath}" ]]; then
    echo "No argument supplied."
    exit 1
fi

# Locate the beginning of the video
ofs=$(grep --byte-offset --only-matching --text "ftypmp4\|ftypisom" "${originalFilePath}"  || true)
# 3681584:ftypisom -> 3681584
ofs=${ofs%:*}

if [[ -n "$ofs" ]] && [[ "$ofs" != 0 ]]; then
  # Copy from ftyp (4 bytes before ofs) to outputfile, skip header
  # Alternative:
  # EXIF: Directory Item Length 
  # bs={filelen-Directory Item Length}
  # https://github.com/GrapheneOS/Camera/issues/75
  dd "if=${originalFilePath}" "of=${originalFilePath%.MP.jpg}.mp4" bs=$((ofs - 4)) skip=1
  
  if command -v termux-media-scan >/dev/null; then
    termux-media-scan -r "${originalFilePath%.MP.jpg}.mp4"
  fi
  
  echo "extracted video from motion photo to ${originalFilePath%.MP.jpg}.mp4"
else
    echo "No video found in file $originalFilePath"
    exit 2
fi